import math

GAMMA_COUNT = 12332
HADRON_COUNT = 6688
TOTAL_COUNT = GAMMA_COUNT + HADRON_COUNT
TEST_SAMPLES_COUNT = math.floor(0.3 * TOTAL_COUNT)
TRAINING_SAMPLES_COUNT = TOTAL_COUNT - TEST_SAMPLES_COUNT
LABEL_INDEX_IN_LINE = 10
SEED = 1
MIN_N_NEIGHBOUR = 1
MAX_N_NEIGHBOUR = 100
MIN_N_ESTIMATE = 1
MAX_N_ESTIMATE = 250
MEAN_VALUE_OF_CROSS_VALIDATION = 'Mean value of cross validation score'
OUTPUT_DIRECTORY = 'output'
TEST_SIZE = 0.3
WORK_BOOK_PATH = './output/data.xls'

F1_SCORE = 'F1 score'
RECALL_SCORE = 'Recall score'
PRECISION_SCORE = 'Precision score'
CONFUSION_MATRIX = 'Confusion matrix'
SCORE = 'Score'
MICRO = 'micro'
MACRO = 'macro'
WEIGHTED = 'weighted'
